on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:

jobs:
  build:
    uses: visciang/gha-elixir-workflow/.github/workflows/elixir.yml@v1
    with:
      image: hexpm/elixir:1.17.3-erlang-27.1-debian-bookworm-20240926
    secrets: inherit
